### ISSUE TITLE
Feature request: hide or resize floating video

### ISSUE THREAD

**Issue by ghost** [Circularify/Seek-n-Play#13]

**Comment by martijnlentink** [comment]
Hi Floris,

It has been some time. But we are planning to implement this feature in coming version. We are currently testing our implementation. Again thank you for your support!

**Comment by florishooft** [comment]
Cool, thanks for updating me!

When I tried to re-enable the extensions I get this warning:


I'm concerned about "Read and change all your data on the websites you
visit" and "Communicate with cooperating websites". Could you elaborate on
those permissions?

Thanks,
Floris

**Comment by martijnlentink** [comment]
Hi Floris,

Thank you for your response. The warning is related to new permissions we added to our extension. With our newest release we implemented a new feature called Seek 'n Play Anywhere(http://circularify.com/seek-n-play-anywhere/). Whilst it is still in beta we want to everyone to try it out! It enables our player to be persistent throughout every tab you use, and this requires the permission to change data on the websites you visit. 

The communication is essentially communication with the YouTube page, where we connect the code running on the page with that on the extensions background.

We are currently looking into the possibility in making the former permission optional, but since we are combining the maintenance of the extension with our full time jobs, please bear with us that things may seem to take a while.

If you have any questions regarding this or anything else, don't hesitate to ask!

-- Martijn

**Comment by martijnlentink** [comment]
Hi Floris,

Thank you for your response. The warning is related to new permissions we added to our extension. With our newest release we implemented a new feature called Seek 'n Play Anywhere(http://circularify.com/seek-n-play-anywhere/). Whilst it is still in beta we want to everyone to try it out! It enables our player to be persistent throughout every tab you use, and this requires the permission to change data on the websites you visit.

The communication is essentially communication with the YouTube page, where we connect the code running on the page with that on the extensions background.

We are currently looking into the possibility in making the former permission optional, but since we are combining the maintenance of the extension with our full time jobs, please bear with us that things may seem to take a while.

If you have any questions regarding this or anything else, don't hesitate to ask!

-- Martijn

________________________________

**Comment by dickwolff** [comment]
Implemented in v2.4.1
